# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.crkyeiaweoy9.ap-southeast-2.rds.amazonaws.com:3306/skkuwhere?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: skku.edu

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml